### ISSUE TITLE
Adding locations in the search box

### ISSUE THREAD

**Issue by saidabou** [HCDX/SpongeBase#10]
I have found this dataset from NGA (National Geospatial Agency), it has transliterations . Shall we add it? 
https://www.dropbox.com/s/l93j0w0be87m8bq/locations_lebanon.xlsx?dl=0

**Comment by saidabou** [comment]
any comments on this previous issue?

**Comment by jamescw** [comment]
Looks like a fine idea to me, @JadGhosn what you think?
